# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# https://docs.gha-runners.nvidia.com/apps/copy-pr-bot/#configuration

enabled: true
