variables:
  # project specific variables
  DRIVER_VERSION: "450.80.02"
  GIT_SSL_NO_VERIFY: "true"
  TF_VERSION: "0.12.18"

stages:
  - syntax-check
  - docker-images
  - build
  - test
  - scan
  - deploy
  - release

shellcheck:
  stage: syntax-check
  image:
    name: koalaman/shellcheck-alpine
  services: []
  before_script: []
  script:
    - shellcheck --version
    - shellcheck --external-sources ci/run.sh
    - shellcheck --external-sources ci/build.sh
  except:
    - schedules
