# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include:
    - local: '.common-ci.yml'

default:
  tags:
    - cnt
    - container-dev
    - docker/multi-arch
    - docker/privileged
    - os/linux
    - type/docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  # Release "devel"-tagged images off the master branch
  # Disabling this for now
  RELEASE_DEVEL_BRANCH: "DISABLED"
  DEVEL_RELEASE_IMAGE_VERSION: "devel"
  # Define the public staging registry
  STAGING_REGISTRY: registry.gitlab.com/nvidia/container-images/driver/staging
  STAGING_VERSION: "${CI_COMMIT_SHORT_SHA}"

.image-pull:
  # Perform for each DRIVER_VERSION
  extends:
    - .driver-versions
  stage: image-build
  variables:
    IN_REGISTRY: "${STAGING_REGISTRY}"
    IN_IMAGE_NAME: driver
    IN_VERSION: "${STAGING_VERSION}"
    OUT_REGISTRY_USER: "${CI_REGISTRY_USER}"
    OUT_REGISTRY_TOKEN: "${CI_REGISTRY_PASSWORD}"
    OUT_REGISTRY: "${CI_REGISTRY}"
    OUT_IMAGE_NAME: "${CI_REGISTRY_IMAGE}"
  # We delay the job start to allow the public pipeline to generate the required images.
  when: delayed
  start_in: 30 minutes
  timeout: 30 minutes
  retry:
    max: 2
    when:
      - job_execution_timeout
      - stuck_or_timeout_failure
  before_script:
    - !reference [.regctl-setup, before_script]
    # We ensure that the DRIVER_VERSION is set
    - 'echo DRIVER_VERSION: ${DRIVER_VERSION} ; [[ -n "${DRIVER_VERSION}" ]] || exit 1'
    - apk add --no-cache make bash
    - regctl manifest get ${IN_REGISTRY}/${IN_IMAGE_NAME}:${IN_VERSION}-${DRIVER_VERSION}-${DIST} --list > /dev/null && echo "${IN_REGISTRY}/${IN_IMAGE_NAME}:${IN_VERSION}-${DRIVER_VERSION}-${DIST}" || ( echo "${IN_REGISTRY}/${IN_IMAGE_NAME}:${IN_VERSION}-${DRIVER_VERSION}-${DIST} does not exist" && sleep infinity )
  script:
    - regctl registry login "${OUT_REGISTRY}" -u "${OUT_REGISTRY_USER}" -p "${OUT_REGISTRY_TOKEN}"
    - make IMAGE_NAME=${IN_REGISTRY}/${IN_IMAGE_NAME} VERSION=${IN_VERSION} OUT_VERSION=${IN_VERSION} push-${DIST}-${DRIVER_VERSION}

image-ubuntu18.04:
  extends:
    - .image-pull
    - .dist-ubuntu18.04

image-ubuntu20.04:
  extends:
    - .image-pull
    - .dist-ubuntu20.04

image-rhcos4.9:
  extends:
    - .image-pull
    - .dist-rhcos4.9

image-rhcos4.10:
  extends:
    - .image-pull
    - .dist-rhcos4.10

image-centos7:
  extends:
    - .image-pull
    - .dist-centos7

# The .scan step forms the base of the image scan operation performed before releasing
# images.
.scan:
  # Repeat for each DRIVER_VERSION
  extends:
    - .driver-versions
  stage: scan
  image: "${PULSE_IMAGE}"
  variables:
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}"
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]scans?\]/i
    - $SKIP_SCANS && $SKIP_SCANS == "yes"
  before_script:
    # We ensure that the DRIVER_VERSION is set
    - 'echo DRIVER_VERSION: ${DRIVER_VERSION} ; [[ -n "${DRIVER_VERSION}" ]] || exit 1'
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker pull --platform="${PLATFORM}" "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}-${DRIVER_VERSION}-${DIST}"
    - docker save "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}-${DRIVER_VERSION}-${DIST}" -o "${DRIVER_VERSION}-${DIST}.tar"
    - AuthHeader=$(echo -n $SSA_CLIENT_ID:$SSA_CLIENT_SECRET | base64 -w0)
    - >
      export SSA_TOKEN=$(curl --request POST --header "Authorization: Basic $AuthHeader" --header "Content-Type: application/x-www-form-urlencoded" ${SSA_ISSUER_URL} | jq ".access_token" |  tr -d '"')
    - if [ -z "$SSA_TOKEN" ]; then exit 1; else echo "SSA_TOKEN set!"; fi
  script:
    - pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN scan -i "${DRIVER_VERSION}-${DIST}.tar" -p $CONTAINER_POLICY -o
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - pulse-cli.log
      - licenses.json
      - sbom.json
      - vulns.json
      - policy_evaluation.json

# Define the scan targets
scan-ubuntu18.04-amd64:
  extends:
    - .scan
    - .dist-ubuntu18.04
    - .platform-amd64
  needs:
    - image-ubuntu18.04

scan-ubuntu20.04-amd64:
  extends:
    - .scan
    - .dist-ubuntu20.04
    - .platform-amd64
  needs:
    - image-ubuntu20.04

scan-ubuntu20.04-arm64:
  extends:
    - .scan
    - .dist-ubuntu20.04
    - .platform-arm64
  needs:
    - image-ubuntu20.04

scan-rhcos4.9-amd64:
  extends:
    - .scan
    - .dist-rhcos4.9
    - .platform-amd64
  needs:
    - image-rhcos4.9

scan-rhcos4.9-arm64:
  extends:
    - .scan
    - .dist-rhcos4.9
    - .platform-arm64
  needs:
    - image-rhcos4.9

scan-rhcos4.10-amd64:
  extends:
    - .scan
    - .dist-rhcos4.10
    - .platform-amd64
  needs:
    - image-rhcos4.10

scan-rhcos4.10-arm64:
  extends:
    - .scan
    - .dist-rhcos4.10
    - .platform-arm64
  needs:
    - image-rhcos4.10

scan-centos7-amd64:
  extends:
    - .scan
    - .dist-centos7
    - .platform-amd64
  needs:
    - image-centos7

# Define the external release helpers
.release:ngc:
  extends: .release:external
  variables:
    OUT_REGISTRY_USER: "${NGC_REGISTRY_USER}"
    OUT_REGISTRY_TOKEN: "${NGC_REGISTRY_TOKEN}"
    OUT_REGISTRY: "${NGC_REGISTRY}"
    OUT_IMAGE_NAME: "${NGC_REGISTRY_IMAGE}"
    # Disable external releases for now
    DOCKER: echo docker
    REGCTL: echo regctl

release:ngc-ubuntu18.04:
  extends:
    - .release:ngc
    - .dist-ubuntu18.04

release:ngc-ubuntu20.04:
  extends:
    - .release:ngc
    - .dist-ubuntu20.04

release:ngc-rhcos4.9:
  extends:
    - .release:ngc
    - .dist-rhcos4.9

release:ngc-rhcos4.10:
  extends:
    - .release:ngc
    - .dist-rhcos4.10

release:ngc-centos7:
  extends:
    - .release:ngc
    - .dist-centos7
