#!/bin/bash

echo "Generating kernel_version.txt"

# Supported NVIDIA driver versions
: ${DRIVER_BRANCH:=525}

# Ubuntu LTS kernels currently are 5.13 and 5.15
# see https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle
: ${LTS_KERNEL:=5.15}
: ${KERNEL_FLAVOR:=generic}
SUPPORTED_KERNELS=""

# Silent apt update
export DEBIAN_FRONTEND=noninteractive
apt-get update -y -qq > /dev/null

# Generate a list of all kernel versions which have NVIDIA precompiled driver packages available.
SUPPORTED_KERNELS=$(apt-cache search linux-objects-nvidia-${DRIVER_BRANCH}-server.*${LTS_KERNEL}.*${KERNEL_FLAVOR} | awk '{print $1}' | grep -v "open" | sed -e "s/^.*${LTS_KERNEL}/${LTS_KERNEL}/" | sort -n -t'-' -k2)

# Grab latest driver version for nvidia-utils-${DRIVER_BRANCH}-server
DRIVER_VERSION=$(apt-cache show nvidia-utils-${DRIVER_BRANCH}-server |grep Version |awk '{print $2}' | cut -d'-' -f1 | head -n 1)

# Latest supported kernel
# only consider suffix -KERNEL_FLAVOR not KERNEL_FLAVOR-* (e.g. KERNEL_FLAVOR-lowlatency)
SK=$(echo "$SUPPORTED_KERNELS" | awk -v f="$KERNEL_FLAVOR" '$0 ~ "-" f "$" {last=$0} END{print last}')

# Write to file
echo "export KERNEL_VERSION=$SK DRIVER_VERSION=$DRIVER_VERSION DRIVER_VERSIONS=$DRIVER_VERSION" > /var/kernel_version.txt
echo "KERNEL_VERSION=$SK DRIVER_VERSION=$DRIVER_VERSION DRIVER_VERSIONS=$DRIVER_VERSION"
