#!/bin/bash

echo "Generating kernel_version.txt"

# Supported NVIDIA driver versions
: ${DRIVER_BRANCH:=525}

# Ubuntu LTS kernels currently are 5.13 and 5.15
# see https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle
: ${LTS_KERNEL:=5.15}
: ${KERNEL_FLAVOR:=generic}
SUPPORTED_KERNELS=""

# Silent apt update
export DEBIAN_FRONTEND=noninteractive
apt-get update -y -qq > /dev/null

# Generate a list of all kernel versions which have NVIDIA precompiled driver packages available.
SUPPORTED_KERNELS=$(apt-cache search linux-objects-nvidia-${DRIVER_BRANCH}-server.*${LTS_KERNEL}.*${KERNEL_FLAVOR} | awk '{print $1}' | grep -v "open" | sort | sed -e "s/^.*${LTS_KERNEL}/${LTS_KERNEL}/")

# Grab latest driver version for nvidia-utils-${DRIVER_BRANCH}-server
DRIVER_VERSION=$(apt-cache show nvidia-utils-${DRIVER_BRANCH}-server |grep Version |awk '{print $2}' | cut -d'-' -f1 | head -n 1)

# Latest supported kernel
SK=$(echo $SUPPORTED_KERNELS | awk '{print $NF}')

# Write to file
echo "export KERNEL_VERSION=$SK DRIVER_VERSION=$DRIVER_VERSION DRIVER_VERSIONS=$DRIVER_VERSION" > /var/kernel_version.txt
echo "KERNEL_VERSION=$SK DRIVER_VERSION=$DRIVER_VERSION DRIVER_VERSIONS=$DRIVER_VERSION"
